name: Docker Publish CI visual_relation
on: [push]

jobs:
  knative:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull images
        run: make pullknative
      - name: Login registry
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_REGISTRY }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag images
        run: make tagknative
      - name: Push images
        run: make pushknative
